auth/urls.py
from django.urls import path

from .views import LoginView, LogoutView, RegisterView

app_name = 'auth'

urlpatterns = (
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
)

author/urls.py
from django.urls import path

from .views import AuthorListView, AuthorDetailView

app_name = 'author'

urlpatterns = (
    path('', AuthorListView.as_view(), name='index'),
    path('<slug>/', AuthorDetailView.as_view(), name='detail')
)

landing/urls.py
from django.urls import path

from landing.views import HomeView

app_name = 'landing'

urlpatterns = (
    path('', HomeView.as_view(), name='home'),
)

publisher/urls.py
from django.urls import path

from .views import PublisherListView, PublisherDetailView

app_name = 'publisher'

urlpatterns = (
    path('', PublisherListView.as_view(), name='index'),
    path('<slug>/', PublisherDetailView.as_view(), name='detail')
)

store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landing.urls')),
    path('auth/', include('auth.urls')),
    path('authors/', include('author.urls')),
    path('books/', include('book.urls')),
    path('publishers/', include('publisher.urls')),
    path('admin/', admin.site.urls),
]

# Admin
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_HEADER

templates/includes/footer.html
{% load i18n %}

<footer class="bg-dark py-3" id="main-footer">
    <div class="container" id="footer-content">
        <div class="text-center text-muted">
            {% trans 'All rights reserved' %} &copy; 2020
        </div>
    </div>
</footer>

templates/includes/header.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark {% if not title %}mb-4{% endif %}">
  <div class="container">
    <a class="navbar-brand" href="{% url 'landing:home' %}">Bookstore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'author:index' %}">{% trans 'Authors' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'publisher:index' %}">{% trans 'Publishers' %}</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:logout' %}">
              <i class="fa fa-sign-out"></i>
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:login' %}">
              <i class="fa fa-sign-in"></i>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load i18n %}

{% if is_paginated %}
  {% with q=request.GET.q %}
    <nav class="mx-auto">
      <ul class="pagination mx-auto">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?page=1{% if q %}&q={{ q }}{% endif %}" class="page-link">
              {% trans 'First' %}
            </a>
          </li>
          <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}{% if q %}&q={{ q }}{% endif %}" class="page-link">
              {% trans 'Previous' %}
            </a>
          </li>
        {% endif %}

        <li class="page-item active">
          <span class="page-link">
            {{ page_obj.number }} / {{ paginator.num_pages }}
            <span class="sr-only">(current)</span>
          </span>
        </li>

        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}{% if q %}&q={{ q }}{% endif %}" class="page-link">
              {% trans 'Next' %}
            </a>
          </li>
          <li class="page-item">
            <a href="?page={{ paginator.num_pages }}{% if q %}&q={{ q }}{% endif %}" class="page-link">
              {% trans 'Last' %}
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endwith %}
{% endif %}

templates/includes/title-default.html
{% if title %}
  <div class="border-bottom mb-4 bg-white">
    <div class="container text-center py-3">
      <h1 class="h5 mb-0">{{ title }}</h1>
    </div>
  </div>
{% endif %}